apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: staging
  labels:
    environment: dev
  annotations:
    customid1: 998123hjhsad
spec:
  containers:
  - name: my-app-container
    image: busybox

