apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on.
      targetPort: 80 # The target port on the pods to forward to.
